### ISSUE TITLE
Home Page Update

### ISSUE THREAD

**Issue by badi3a** [badi3a/TwinIm#7]
**Task:** Update the home page to include a search form with a slide and implement search functionality.

Details:

- Design a slideshow on the home page that showcases featured announcements or promotional content.
- Add a search form within the slide, allowing users to input various criteria to search for announcements (e.g., name, price, location, etc.).
- When the user clicks the search button, they should be redirected to the ListComponent where the list of filtered announcements will be displayed based on the search parameters.
- The search criteria should be passed as query parameters in the URL (e.g., /announcements?name=value&price=value).
- Ensure the search form is user-friendly and includes necessary validations for each input field.
- Maintain responsive design so that both the slide and search form look great on all screen sizes.

**Comment by Youssef-BS** [comment]
bonjour , 
J'ai rencontré un problème en essayant de transférer mes récentes modifications vers mon branch Git. Le message d'erreur indique que ma succursale locale est derrière l'homologue distant, il est dit : Updates were rejected because the tip of your current branch is behind its remote counterpart.
